server:
  port: 8088

spring:
  application:
    name: account-service

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

accountservice:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springcloud
    uname: cassandra
    passwd: cassandra


