server:
  port: 8088

spring:
  application:
    name: account-service
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: http://localhost:8098

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

accountservice:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springcloud
    uname: cassandra
    passwd: cassandra

management:
  endpoints:
    web:
      exposure:
        include: "*"


