
server:
  port: 9999

spring:
  application:
    name: eureka-discover-server

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/