server:
  port: 8091

spring:
  application:
    name: notification-service
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: http://localhost:8508
  rabbitmq:
    username: "triusqueue"
    password: "triusqueue"
  cloud:
    stream:
      bindings:
        input:
          destination: "triusqueue"

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"