server:
  port: 8091

spring:
  application:
    name: notification-service

  rabbitmq:
    username: "triusqueue"
    password: "triusqueue"

  cloud:
    stream:
      bindings:
        input:
          destination: "triusqueue"

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/